name: Deploy Dockerized App to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t saimaali079/docker:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push saimaali079/docker:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull latest image
            docker pull saimaali079/docker:latest

            # Stop current container if exists
            docker rm -f my_app || true

            # Run new container
            docker run -d --name my_app -p 80:80 saimaali079/docker:latest